### ISSUE TITLE
rename to assisted-service-operator-chart

### ISSUE THREAD

**Issue by mhrivnak** [open-cluster-management/assisted-service-chart#2]
This chart does not deploy the assisted-service, so it could be confusing or even misleading to call it the "assisted-service-chart". Likewise the chart itself has a name and description that reference the service instead of the operator:

```
apiVersion: v2
appVersion: 1.16.0
description: Assisted Service is used to orchestrate baremetal OpenShift installations.
name: assisted-service
type: application
version: 2.3.0
```

I suggest naming this chart the "assisted-service-operator", which matches the name of the bundle that it takes the place of.

**Comment by nathanweatherly** [comment]
Thanks for the input!

This chart is internal to the product-- the customer never interacts directly with this chart. With that being said, we'll discuss with the chart owners (assisted service people) and follow up 👍

**Comment by nathanweatherly** [comment]
Closing as dup of https://github.com/open-cluster-management/backlog/issues/12654
